name: weather data pipeline

on:
  workflow_dispatch:

jobs:
  autorun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode JSON credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIAL }}" | base64 -d > /tmp/GOOGLE_CREDENTIAL.json

      - name: Run Python script
        run: |
          python main.py
        env:
          GOOGLE_CREDENTIAL: /tmp/GOOGLE_CREDENTIAL.json
          API_TOKEN: ${{ secrets.API_TOKEN }}
