# name: weather data pipline

# on:
#   workflow_dispatch:

# jobs:
#   autorun:
#     runs-on:ubuntu-latest
#     steps:

#     - name: checkout rep content 
#       uses: actions/checkout@v4

#     - name: setup python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.9"
#         cashe: "pip"

#     - name: cashe ubuntu dependencies
#       uses: actions/cashe@v3
#       with:
#         path: ~/.cache/pip
#         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#         restore-keys: |
#           ${{ runner.os }}-pip-

#     - name: install dependencies
#       run: 
#         python -m pip install -- upgrade pip
#         pip install -r requirements.txt

#     - name: decode json file
#       run: |
#         echo "${{ secrets.GOOGLE_CREDENTIAL }}" | base64 -d > /tmp/GOOGLE_CREDENTIAL.json

name: weather data pipeline

on:
  workflow_dispatch:

jobs:
  autorun:
    runs-on: ubuntu-latest

    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}  # Pass API token to Python via env variable

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Google Credentials JSON
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIAL }}" | base64 -d > /tmp/GOOGLE_CREDENTIAL.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_CREDENTIAL.json
          python main.py
